### PR TITLE
dev-4330: add Supplier Data Manager API doc

### PR DESCRIPTION
**Pull request by PierrickMartos**
image

### CODE REVIEW

**Comment by akeneo-secops** [comment]
### Gitleaks PR check
🟢 We detected no secrets within this PR! Good job 🎉

**Review by AnnaPeris-akeneo — CHANGES_REQUESTED** [review]
Hello Pierrick, leaving my feedback here: 
- Menu: the title is not aligned as per the left side padding 
- the footer and last paragraph of the getting starting have not the right font color, or there is a weird colour
I enclosed screenshots
2024-09-26_16h22_40
2024-09-26_16h23_16
Thanks!

**Comment by PierrickMartos** [comment]
@AnnaPeris-akeneo Weird I fixed locally but it didn't worked online, now it's OK. THanks!

**Review by AnnaPeris-akeneo — APPROVED** [review]
Yep, works for me!

**Pull request merged**
