### PR TITLE
fix api-rest filter example

### PR DESCRIPTION
**Pull request by oallain**
| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | no
| Added Behats                      | no
| Changelog updated                 | no
| Review and 2 GTM                  |  no
| Migration scripts                 | no
| Tech Doc                          | yes

An error has crept into an example.

### CODE REVIEW

**Comment by oallain** [comment]
Ping @ValentinMumble

**Comment by ValentinMumble** [comment]
@oallain 😍 Thanks for taking the time to contribute! You're awesome! 😍

We gladly welcome any kind of contributions, fix typos, glitches, bugs, technical enhancement.

We do our best to ease contributions as much as we can, feel free to open an issue to start a discussion, a core developer will help you.

To be able to merge your contribution, we need that you read and sign the following contributor agreement http://www.akeneo.com/contributor-license-agreement/

You can follow this guide to have details about how to contribute: https://docs.akeneo.com/master/contribute_to_pim/contribution_guide.html

**Comment by oallain** [comment]
Hi @ValentinMumble ,

Thanks for your answer.
I have sign the following contributor agreement :rocket: 

I thinks all is right, yes ?

**Comment by ValentinMumble** [comment]
> I thinks all is right, yes ?

Perfect, everything is alright, thank you again!

**Pull request merged**
