### PR TITLE
CHA-592: improve the documentation

### PR DESCRIPTION
**Pull request by hogren**
With this PR:
- I updated links and examples with version 1.0.3 of the meta-schema.
- I added a link between API reference and the documentation for creating a JSON Schema.
image

- I add a few line of documentation about creating a mapping schema. It's not exhaustive at all but I think it's really better than before.
image

### CODE REVIEW

**Comment by akeneo-secops** [comment]
### Gitleaks PR check
🟢 We detected no secrets within this PR! Good job 🎉

**Comment by AdelELHAIBA-Akeneo** [comment]
Good for me :smile: 

One comment, if we can to align the bracket it can be good

image

**Review by AdelELHAIBA-Akeneo — APPROVED** [review]

**Comment by hogren** [comment]
> Good for me 😄
> 
> One comment, if we can to align the bracket it can be good
> 
> image

It's a general problem in api-doc. I did not spend time to find a solution (readme.io is coming).

**Comment by AdelELHAIBA-Akeneo** [comment]
> > Good for me 😄
> > One comment, if we can to align the bracket it can be good
> > image
> 
> It's a general problem in api-doc. I did not spend time to find a solution (readme.io is coming).

@hogren you have just to add an empty line on the first line and that's it :smile: 
Here is some examples https://api.akeneo.com/graphql/use-cases.html

**Review by yvesmotteux — APPROVED** [review]

**Comment by hogren** [comment]
> > > Good for me 😄
> > > One comment, if we can to align the bracket it can be good
> > > image
> > 
> > 
> > It's a general problem in api-doc. I did not spend time to find a solution (readme.io is coming).
> 
> @hogren you have just to add an empty line on the first line and that's it 😄 Here is some examples https://api.akeneo.com/graphql/use-cases.html

@AdelELHAIBA-Akeneo done ! Thank you for the tips.

**Pull request merged**
